//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloodBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First register yourself with !register. After registering you&apos;ll be given 100★ with which you can bet on any of the scheduled games. You can see what games are scheduled with the command !matches. You may bet on a match up until it starts, the moment it starts bets will be locked.
        ///
        ///You can either bet on the outcome of a game or the score. The outcome of a game is what team wins it, or if it&apos;s a tie. Outcome can either be A, B, or T. A is team A winning. B is team B winning. T is a tie. The score is the fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HowIsBetFormed {
            get {
                return ResourceManager.GetString("HowIsBetFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payouts are made proportionally. For example, if you wager $1 on outcome A and the total pot for outcome A 1 is $4, your proportion is 25%. This means that you are entitled to 25% of the outcome B+T pot, assuming that outcome A wins. Your proportion of the payout is calculated as follows: (Your bet/Total amount bet on the outcome). If you guess the score right, then your 25% of the outcome B+T pot is doubled..
        /// </summary>
        internal static string HowIsPayoutCalculated {
            get {
                return ResourceManager.GetString("HowIsPayoutCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a match finishes, winners and losers are resolved through their bet outcome. Those who got the outcome right win, and those who didn&apos;t, lose. The winners who bet on the right score have the money corresponding to their % of the pot doubled. 
        ///If there were winners but there were no losers, all the money is refunded..
        /// </summary>
        internal static string HowIsWinnerBorn {
            get {
                return ResourceManager.GetString("HowIsWinnerBorn", resourceCulture);
            }
        }
    }
}
